import 'package:flutter/material.dart';

class Product {
  final String? image, title, origin, description;
  final int? price, id;
  final Color? color;

  Product({
    this.id,
    this.image,
    this.title,
    this.price,
    this.origin,
    this.description,
    this.color,
  });
}

List<Product> products = [
  Product(
      id: 1,
      title: "Pendant Dangle Earring",
      price: 259,
      origin: "BD",
      description: dummyText,
      image: "assets/images/1.png",
      color: Color(0xFF6F787D)),
  Product(
      id: 2,
      title: "Sterling Silver Green Cat Eyes Korean White Fungus",
      price: 1155,
      origin: "USA",
      description: dummyText,
      image: "assets/images/2.png",
      color: Color(0xFF141518)),
  Product(
      id: 3,
      title: "Jhumka Earrings",
      price: 350,
      origin: "CN",
      description: dummyText,
      image: "assets/images/3.png",
      color: Color(0xFF712C1D)),
  Product(
      id: 4,
      title: "Crystal Necklaces",
      price: 199,
      origin: "BD",
      description: dummyText,
      image: "assets/images/4.png",
      color: Color(0xFFAA220A)),
  Product(
      id: 5,
      title: "Crystal Flower Bracelet",
      price: 317,
      origin: "BD",
      description: dummyText,
      image: "assets/images/5.png",
      color: Color(0xFFF80205)),
  Product(
    id: 6,
    title: "Ethnic Style Earring Pendant",
    price: 343,
    origin: "IND",
    description: dummyText,
    image: "assets/images/6.png",
    color: Color(0xFF6A035B),
  ),
  Product(
    id: 7,
    title: "Earrings Jhumka Earrings",
    price: 355,
    origin: "BD",
    description: dummyText,
    image: "assets/images/7.png",
    color: Color(0xFF5327E0),
  ),
  Product(
    id: 8,
    title: "Nose Pin L Shape Nosering",
    price: 99,
    origin: "BD",
    description: dummyText,
    image: "assets/images/8.png",
    color: Color(0xFF63D3FA),
  ),
  Product(
    id: 9,
    title: "Crystal Fashion Fake Nose Ring",
    price: 50,
    origin: "USA",
    description: dummyText,
    image: "assets/images/9.png",
    color: Color(0xFF03381B),
  ),
  Product(
    id: 10,
    title: "White Star Zirconia Nose Pin",
    price: 500,
    origin: "CN",
    description: dummyText,
    image: "assets/images/10.png",
    color: Color(0xFF139F02),
  ),
  Product(
    id: 799,
    title: "L Shape Nosering",
    price: 150,
    origin: "CN",
    description: dummyText,
    image: "assets/images/11.png",
    color: Color(0xFFC90F04),
  ),
  Product(
    id: 12,
    title: "Trendy black Nose Pin",
    price: 60,
    origin: "USA",
    description: dummyText,
    image: "assets/images/12.png",
    color: Color(0xFF0178C7),
  ),
  Product(
    id: 13,
    title: "Nath style Adjustable Nose Ring",
    price: 255,
    origin: "CN",
    description: dummyText,
    image: "assets/images/13.png",
    color: Color(0xFFD62862),
  ),
  Product(
    id: 14,
    title: "Simple Nekhless",
    price: 499,
    origin: "BD",
    description: dummyText,
    image: "assets/images/14.png",
    color: Color(0xFFFE5200),
  ),
  Product(
      id: 15,
      title: "Simple Payel",
      price: 250,
      origin: "BD",
      description: dummyText,
      image: "assets/images/15.png",
      color: Color(0xFFCCB28D)),
  Product(
      id: 16,
      title: "Payel",
      price: 99,
      origin: "USA",
      description: dummyText,
      image: "assets/images/16.png",
      color: Color(0xFFF5E773)),
  Product(
      id: 17,
      title: "Bala",
      price: 4990,
      origin: "CN",
      description: dummyText,
      image: "assets/images/17.png",
      color: Color(0xFF9ABD44)),
  Product(
      id: 18,
      title: "Yellow Churi",
      price: 600,
      origin: "BD",
      description: dummyText,
      image: "assets/images/18.png",
      color: Color(0xFF70E66C)),
  Product(
      id: 19,
      title: "Stone Churi",
      price: 250,
      origin: "USA",
      description: dummyText,
      image: "assets/images/19.png",
      color: Color(0xFFFB7883)),
  Product(
    id: 20,
    title: "Simple Ring",
    price: 199,
    origin: "IND",
    description: dummyText,
    image: "assets/images/20.png",
    color: Color(0xFFBA855A),
  ),
  Product(
    id: 21,
    title: "Stone Ring",
    price: 1750,
    origin: "BD",
    description: dummyText,
    image: "assets/images/21.png",
    color: Color(0xFFF7EF8D),
  ),
  Product(
    id: 22,
    title: "Diamond Ring",
    price: 27800,
    origin: "BD",
    description: dummyText,
    image: "assets/images/22.png",
    color: Color(0xFFF7EF8D),
  ),
  Product(
    id: 23,
    title: "Black Silver Diamond Ring",
    price: 499000,
    origin: "USA",
    description: dummyText,
    image: "assets/images/23.png",
    color: Color(0xFFF2B576),
  ),
  Product(
    id: 24,
    title: "Queen Ring",
    price: 37500,
    origin: "CN",
    description: dummyText,
    image: "assets/images/24.png",
    color: Color(0xFFF2B576),
  ),
  Product(
    id: 25,
    title: "Nekhless for Bride",
    price: 6999999,
    origin: "CN",
    description: dummyText,
    image: "assets/images/25.png",
    color: Color(0xFFE26B40),
  ),
  Product(
    id: 26,
    title: "Diamond Nekhless",
    price: 775,
    origin: "USA",
    description: dummyText,
    image: "assets/images/26.png",
    color: Color(0xFFEB9392),
  ),
  Product(
    id: 27,
    title: "Simple Ornaments",
    price: 675,
    origin: "CN",
    description: dummyText,
    image: "assets/images/27.png",
    color: Color(0xFFEB9392),
  ),
  Product(
    id: 28,
    title: "Diamond Nekhless with green stone",
    price: 299,
    origin: "BD",
    description: dummyText,
    image: "assets/images/28.png",
    color: Color(0xFFAAC585),
  ),
];

String dummyText =
    "Ornaments help us to identify and locate, tell or communicate, remind and organise our action, they guide our attention, express and individualise, can generate an experience, beautify as well as re-present.";
